src/raygun.js

This should fix #116. It might be worth locking down the allowable error codes even further, but I'm not sure which status codes should trigger it.

Fix for #116 (Don't stash errors rejected with HTTP 429 in localStorage)

---

typescript/index.d.ts
typescript/raygun4js-tests.ts

Update the Raygun4JS typescript definition to reflect new breadcrumb work.

Update Typescript definition

---

src/raygun.utilities.js

For some reason the node type of a button is "submit" which currently causes the nodeText utility function to try and retrieve the text via the `value` property. This updates that logic to fall back to `nodeText`/`textContent` if `value` is falsey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/269)

Correctly record button text for click event breadcrumbs

---

src/raygun.breadcrumbs.js
src/raygun.js

If the `all` method in the Breadcrumbs module encounters an error the error handling function it is wrapped with will return undefined. In raygun.js when we retrieve the breadcrumbs to push them onto the error payload it is assumed that at least an empty array is returned. This attempts to fix any potential processing errors in the `all` method and ensures at least an empty array is used when iterating over the breadcrumbs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/275)

Fix crash populating breadcrumbs when _breadcrumbs.all() errors

---

src/raygun.utilities.js

Return clone when using mergeArray. This prevents object mutation bugs, like Unhandled Exception tag being added to subsequent errors.

Always return a new object when using merge array

---

src/raygun.loader.js

In Ember environments, arrays would cause the `for..in` loop to break due to extra properties.
https://github.com/emberjs/ember.js/issues/553

fix for arrays getting filled with extra properties from Ember

---

CHANGELOG.md
package.json
src/raygun.js

Don't load RUM in React Native environment. It won't work correctly anyway as we don't have access to the requisite browser APIs.
Re #310 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/323)

Fix RUM crash in React Native

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum.js
src/raygun.utilities.js
tests/specs/v2/rumXhrStatusTracking.js

- Change the key for the status code which gets sent to RUM to `statusCode` to match the API
- Prepend the protocol to the URL in the `resolveFullUrl` function to accommodate URLs without protocols

Change status code name and fix URL protocol

---

src/raygun.network-tracking.js

On a fetch call, sometimes the body can't be read when calling text().
Wrap the code that tries to do this in a try/catch as it is unessential
code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/330)

fix(network-tracking): catch exceptions when reading body text()

---

src/raygun.rum.js

Adds `first-paint` and `first-contentful-paint` data onto the page performance entry using the performance API and `msFirstPaint` for Edge/IE. Also ignores any paint entries from being sent with timing payloads.

Track paint calls with page timing information

---

CHANGELOG.md
README.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.loader.js
tests/fixtures/common/instrumentXHRs.js
tests/fixtures/v2/withClientIpSet.html
tests/fixtures/v2/withoutClientIpSet.html
tests/specs/v2/clientIp.js

Adds a new option to set the clients IP address. This client IP is sent with all requests under the `X-Remote-Address` header. This is useful for those wishing to proxy requests to Raygun (using the `apiEndpoint` option) but also want to maintain existing functionality.

Add option to set clients ip

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum.js
tests/specs/common.js
tests/specs/sessions/realUserMonitoring.js

Reverts using session storage and instead use local storage to persist the session id. This is because new sessions are created when users open the same domain in different tabs which will associate those pages with new calls, when we want them to be associated with the same session.

Revert sessionstorage to localstoage

---

src/raygun.network-tracking.js

Since I see this log quite often I'd like to see it with correct capitalisation :slightly_smiling_face:

chore: XHR response tracking log capitalisation

---

CHANGELOG.md
README.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.loader.js
src/raygun.rum.js
tests/fixtures/v2/rumFetchPolyfillStatusCodes.html
tests/fixtures/v2/rumFetchStatusCodes.html
tests/fixtures/v2/rumReferencedFetchWithFetchSnippet.html
tests/fixtures/v2/rumXhrStatusCodes.html

Updates how we track XHR & Fetch requests which are missing from the window.performance API and when they are sent to Raygun. These will no longer be sent by default, instead you can configure the `captureMissingRequests` option to enable this setting.
The reason behind this is that the timings for these requests are not as accurate as the performance API (as the functionality relies on listening to event listeners, which can be delayed) and we only have the duration to go on.
Included updates: 
- When collecting timing information any XHR timings which we detect are still 'in-flight' (have had a request but not a response) will be delayed from being sent (until the next collection). This is due to a edge case where the timings can be recorded twice.

Disable tracking XHR requests missing from the performance API by default

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.network-tracking.js
tests/fixtures/v2/rumReferencedFetchWithFetchSnippet.html
tests/specs/v2/rumXhrStatusTracking.js

Updates how Raygun4JS integrates with the fetch network tracking script, fixing a issue when other scripts override the fetch handler.

Network tracking bug fix

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum.js

Description:
FP was being calculated incorrectly for IE/Edge browsers. This PR implements a fix for this by calculating the difference between `ms-firstPaint` and `fetchStart`.

[RUM SUP-21] [BUG] First paint captured incorrectly - Fix

---

yarn.lock

Update js-yaml dependency to fix security vulnerability. 
* Update version for js-yaml from 13.3.0 to 13.3.1
* Delete and re-add yarn.lock

Update yarn.lock for js-yaml

---

src/raygun.js
src/raygun.rum.js

This PR fixes the bug first reported in 2016 in issue #186 
When using `trackEvent` `pageView` (tracking page views in single page apps) telemetry for the last page is never sent. This is because any XHR requests sent in the [beforeunload event handler](https://github.com/MindscapeHQ/raygun4js/blob/master/src/raygun.rum.js#L107) is cancelled before it has a chance to open the connection.
We can fix this by using [navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) if available.
The only difference on Chrome is the standard request headers contain `Sec-Fetch-Mode: cors` but when using sendBeacon this changes to `Sec-Fetch-Mode: no-cors`. Since this is an experimental header it has no effect currently. I don't forsee any future issues as the server …

Use navigator.sendBeacon when document is unloading

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.breadcrumbs.js
src/raygun.rum.js
tests/fixtures/breadcrumbs/automatic.xhr.html
tests/specs/breadcrumbs/automatic.xhr.js

This PR introduces a couple of bug fixes: 
- Ignore navigation types with a 'entryType' of 'navigation'. Previously these were being counted as 'cached child assets'
- Fixes a breadcrumb issue where the `setAutoBreadcrumbsXHRIgnoredHosts` values would be ignored when requests are being opened. Meaning excess breadcrumb values were being logged

Ignore navigation entryTypes and fix breadcrumb XHR requests

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.utilities.js

`node.value` was accidentally removed in a previous PR and is now added back in

Hot fix for missing value

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum/index.js

Fixes an issue where mobile browsers won't send data in when they don't fire the 'beforeunload' event handler. The main browser this affects is Mobile Safari, but this can impact other browsers as well.

Mobile browser bug fix: Send data with the pagehide instead of unload

---

tracekit/tracekit.js

Adds **`ionic`** scheme to Tracekit's error stack parsing regex.
This PR will solve the issue mentioned in: https://github.com/MindscapeHQ/raygun4js/issues/367

Fixes the issue of error not being sent when ionic scheme is used.

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum/index.js
src/raygun.rum/rum.spec.js

Creates a new utility method for retrieving the duration value on performance timing entries. 
When the duration value is not `0` we return that value. When it is zero we attempt to calculate the duration from the `responseEnd - startTime`, which is how [the `duration` value is suppose to work anyhow](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry/duration). 
This resolves an issue in Safari where timings resulting from `fetch` calls will have a `duration` value of 0, when the `responseEnd` and `startTime` have valid entries.

Fallback for duration values of 0

---

src/raygun.js
tests/fixtures/v2/unhandledPromiseRejectionWithNoReason.html
tests/specs/v2/unhandledPromiseRejectionTests.js

Make it easier to distinguish unhandled promise rejection errors from standard script errors by specifying the error message to be "Unhandled promise rejection".
- Set the `error` value to a new Error object with a null stacktrace if no reason or detail is defined when an unhandled rejection event occurs.

Replace unhandled rejection error message

---

CHANGELOG.md
package.json
src/raygun.rum/index.js

This PR fixes an issue where the `xhrStatusMap` array was not being cleared. This has the potential to degrade performance if a session is particularly long.
- Clears the `xhrStatusMap` array on every heartbeat
- Updates changelog/package version
✅ Status codes are being tracked/mapped correctly
✅  Test if the heartbeat could potentially cut off mapping requests to their status code
✅  Test with high volumes of XHR calls
✅  Test performance when sessions are very long

Fix memory issue

---

tracekit/tracekit.js

This adds `app` as a detected url scheme, in the same way as `ionic` , and fixes missing stack traces in Cordova iOS 6 apps.
fixes #379

Update tracekit.js to support app:// url scheme

---

src/raygun.rum/core-web-vitals.js
src/raygun.rum/core-web-vitals.spec.js

This PR ensures that all Core Web Vital metric values are reported back to Raygun as 3dp values, to match how our other timings are being formatted.
- Added formatting logic to payload creation method.
- Added a spec to account for the formatting.

[RUM-661]  Core web vitals - Data formatting

---

README.md
src/raygun.js

This PR will enable Core Web Vital tracking by default, with the option to opt out, so that Raygun is able to report on these new metrics.
Changes made:
- Set default of the `trackCoreWebVitals` option to true.
- Added the option to the readme.
-

Enable Core Web Vital tracking by default

---

CHANGELOG.md
package.json
src/raygun.rum/core-web-vitals.js
src/raygun.rum/vendor/web-vitals-polyfills.vendor.js
src/raygun.rum/vendor/web-vitals.vendor.js

This PR aims to address an issue around Core Web Vitals being initiated for non-browser environments. Fixes #397.
Changes made:
- Ensure window exists before attempting to access the `webVitals` attribute.
- Don't init the web vital scripts when the document does not exist as this means that core web vitals cannot be tracked.

Non-browser environment fixes.

---

CHANGELOG.md
package.json
src/raygun.rum/index.js

This PR fixes an issue where the heartbeat was not clearing the xhrStatusMap array due to `this` referring to the window object

Fix xhr status map memory leak

---

package.json

This PR bumps up the chromedriver version to fix a build issue where we are expecting Chrome 90.x.x

Bump chromedriver version

---

src/raygun.rum/index.js

[APL-37](https://raygun.atlassian.net/browse/APL-37): Release granular customer data for CWV
CWV metrics are being added to the queue when they are captured, and when virtual page timings are added to the queue, they block CWV metrics from being sent. By sending them immediately instead of adding them to the queue, they will always be sent and won't be disrupted by virtual pages.
...
Send core web vital timing metrics immediately instead of adding to them to the queue

Send core web vital timing metrics immediately

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum/index.js
src/raygun.rum/vendor/web-vitals-polyfills.vendor.js
src/raygun.rum/vendor/web-vitals.vendor.js

Upgrade the [web-vitals](https://github.com/GoogleChrome/web-vitals) vendor scripts to the latest version ([v2.1.0](https://github.com/GoogleChrome/web-vitals/releases/tag/v2.1.0)). 
This version includes several updates to the library, including the following notable improvements:
- [Firefox compatibility improvements](https://github.com/GoogleChrome/web-vitals/pull/143/files)
- [CLS tracking improvement](https://github.com/GoogleChrome/web-vitals/pull/149/files) 
- [Only track CLS if FCP is being tracked](https://github.com/GoogleChrome/web-vitals/pull/154/files)
- [web-vitals-polyfills.vendor.js](https://github.com/MindscapeHQ/raygun4js/blob/3a4b0bd93359552a83b94112120534d92578af9b/src/raygun.rum/vendor/web-vitals-polyfills.vendor.js)
- …

Upgrade web-vitals vendor scripts to version 2.1.0

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum/index.js

The `navigator.sendBeacon` function can throw an 'Illegal invocation' error in [certain cases](https://xgwang.me/posts/you-may-not-know-beacon/#it-may-throw-error%2C-be-sure-to-catch). This change suppresses any errors, but logs out the error with details if debugMode has been enabled.
- Wrap the `navigator.sendBeacon` function call with a try-catch, log out the error

Wrap the sendBeacon call to suppress errors

---

CHANGELOG.md
Gruntfile.js
README.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.utilities/errorUtilities.js
src/raygun.utilities/errorUtilities.spec.js
src/raygun.utilities/index.js
src/raygun.utilities/utilities.spec.js
yarn.lock

If an error occurs in a script that is injected into the body of the website's document by an extension, this error can be caught by the `window.onerror` handler. 
From researching this, I've found errors from browser extensions can take on multiple forms. This PR covers three particular cases, with the aim that if a developer wants to ignore third-party errors, these errors should also be ignored.
If the error occurs within a function, then each line of the stacktrace will have a `url` value prefixed with `*-extension://` (where `*` is one of 'chrome', 'safari', 'safari-web', or 'moz').
For example:
```js
{
message: 'Error in a browser extension function',
stack: [
{
line: 12,
column: 345,
url: 'chrome-extension://example/index.js',
func: 'render'
},
]
}
```
There is now a utility …

Discard errors from browser extensions if ignore3rdPartyErrors option is true

---

src/raygun.network-tracking.js

This PR does the same change as #375 but I already made the change before noticing this PR and have some explanation around the fix 😅 
Currently the existing code for `processFetch` calls `originalFetch` and stores the promise, it then attempts to attach a chain to the original promise to fork the promise resolution for raygun specific handling of things. This is fine except the `catch` is attached to the parent promise instead of the new `then` chain which has been added to the original promise. 
This consequently means that if the newly attached `then` chain throws an exception it is not handled.
Original flow:
```
┌──────────────┐
│ processFetch │
└───────┬──────┘
│
▼
┌─────────────────────────────────┐
│                                 │
│           ┌───────────────┐     │
│ …
```

(Bugfix) Resolve issue where calling originalFetch can throw an unhandled rejection.

---

src/umd.intro.js

The rg4js proxy in the umd loader is currently throwing away the return value of the executor. This prevents the use of commands like 'getRaygunInstance'.

Fix rg4js returning undefined when using UMD

---

README.md
src/raygun.loader.js

Previously, if a customer wanted to use `getRaygunInstance`, it would return undefined until raygun4js had finished loading, requiring the customer to add event listeners for load events.
Now, a callback can be passed with 'getRaygunInstance':
```javascript
rg4js('getRaygunInstance', raygunInstance => {
console.log(raygunInstance); // will always be defined
})
```
This simplifies the process of accessing the raygun instance, which is
useful for applications that have multiple raygun instances present.

Allow passing callback with getRaygunInstance

---

tracekit/tracekit.js

Ionic Capacitor now uses the `capacitor://` scheme on iOS which is not included in the regex check which results in stack traces not being parsed correctly on iOS. I have added `capacitor` to the regex and verified that the stack traces are parsed correctly. Here is what the stack looks like on errors thrown from within Capacitor on iOS for reference:
```
cause: – undefined
message: – "Testing"
name: – "Error"
stack: – "Jn@capacitor://localhost/js/index.20.1d828c7a.js:1:134788↵global code@↵evaluateWithScopeExtension@[native code]↵@↵_wrapCall@" (chunk-vendors.20.242c3e64.js, line 3544)
"Jn@capacitor://localhost/js/index.20.1d828c7a.js:1:134788
global code@
evaluateWithScopeExtension@[native code]
@
_wrapCall@"
```
Here is also a link to the project on GitHub showing the official default …

Support for Ionic Capacitor stack traces on iOS

---

CHANGELOG.md
README.md
src/raygun.js

**NOTE: This is not to be merged until we have fully released the name change in the Raygun application. Changes to 'users' within the code needs to be discussed and planned for.**
This PR is to updating the name convention for 'User tracking' to now be 'Customers' to reflect what's within the Raygun application.
**Updates**
👉 Update `README` documentation
👉 Update `CHANGELOG`
👉 Update code comment within `raygun.js`
- Make sure documentation changes are reflected to be 'Customers' instead of 'User Tracking'

[Customers Product]: Change references from 'Users' to 'Customers' within documentation 👥

---

README.md

This PR is to update the raygun4js README to replace documentation for AngularJS (which has reached its EOL in Jan 2022) with relevant documentation for Angular 2+ (more commonly known as just "Angular")

Update Angular documentation in README

---

CHANGELOG.md
README.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.rum/index.js

The `allowInsecureSubmissions` option was necessary to enable http (not s) support on IE8
We no longer support IE8, also IE 8 doesn't support TLS 1.2 
So this functionality is obsolete and needs to be removed
(Removal from the docs is in another PR)
Also removed code for `XDocumentRequest` as this is also (very) obsolete

Remove allowInsecureSubmissions option

---

CHANGELOG.md
V1Documentation.md
bower.json
package-lock.json
package.json
raygun4js.nuspec
src/raygun.js
tests/specs/v1/eventsXhr.js
tests/specs/v1/payloadManualSendTests.js
tests/specs/v1/payloadUnhandledErrorTests.js
tests/specs/v2/eventsXhr.js
tests/specs/v2/onBeforeSendRUM.js
tests/specs/v2/payloadManualSendTests.js
tests/specs/v2/payloadSyntaxError.js
tests/specs/v2/payloadUnhandledErrorTests.js
tests/specs/v2/rg4jsLoaderTests.js

Based off this:
https://github.com/MindscapeHQ/raygun4js/pull/349
[I was unable tp push a rebase from master to that PR/branch]
> This PR changes the default endpoint from api.raygun.io to api.raygun.com as .com is now the recommended endpoint.
https://github.com/MindscapeHQ/raygun4js/pull/349#issue-576533611

Update endpoint from .io to .com

---

.github/workflows/tests.yml
CHANGELOG.md
bower.json
package-lock.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.rum/index.js

- The 'OnBeforeSend' and 'OnBeforeSendRUM' callbacks are now passed a clone of the payload, to prevent accidental pollution of global objects
- Updated the Github Action (Pre commit unit tests) Node to version 20

Create a deep clone of the payload before passing it to a users call back function

---

CHANGELOG.md
bower.json
package-lock.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.utilities/errorUtilities.spec.js
tests/specs/v1/eventsXhr.js
tests/specs/v1/payloadManualSendTests.js
tests/specs/v1/payloadUnhandledErrorTests.js
tests/specs/v2/eventsXhr.js
tests/specs/v2/onBeforeSendRUM.js
tests/specs/v2/payloadManualSendTests.js
tests/specs/v2/payloadSyntaxError.js
tests/specs/v2/payloadUnhandledErrorTests.js
tests/specs/v2/rg4jsLoaderTests.js

- Reverted the default endpoint url from api.raygun.com back to api.raygun.io (From release v2.26.2 which is causing disruptions for some users)

Revert the default endpoint url from api.raygun.com back to api.raygun.io

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js

This change forces the re-sending of stored errors to use the .IO domain name, rather than .COM. Due to the recent issue of changing this, some stored errors are being sent and causing further CSP violations.
This change is to address that issue.

Force .io if URL is not overridden

---

CHANGELOG.md
package-lock.json
package.json

[Ticket](https://raygun.atlassian.net/browse/WORM-248)
Phase 2 of 2 deprecating old packages
(Phase 1 here :https://github.com/MindscapeHQ/raygun4js/pull/499)
This needs to be done from the command line/online.
This is  a 'Line in the sand' commit to mark when we deprecated a number of versions in NPM and Nuget

Darcy/worm 248/deprecated message

---

CHANGELOG.md
bower.json
package-lock.json
package.json
raygun4js.nuspec
src/raygun.loader.js
src/umd.intro.js
tests/fixtures/v2/UMDInfiniteLoop.html
tests/specs/v2/UMDInfiniteLoopTest.js

This PR is to solve an issue first surfaced in issue #473.
We are assuming rg4js is loaded when `document.readyState` is marked as `complete`. However, this is not true, it's not loaded until after the `load` event has been triggered. According to the [spec](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) `complete` indicates that the `load` event is _about_ to fire. This leaves a small gap where if our code is executed between the document state being marked as complete and the `load` event firing, an infinite recursive loop is started that will hang the application. 
The current fix I have in mind for this is to add a variable to the window that is set to true after we know for sure rg4js is initialized. The UMD initialization code will then wait for this rather …

Fix infinite recursive loop on UMD module init

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.loader.js
src/raygun.rum/index.js

This PR is being developed in conjunction with updates to the RUM worker that allows for client information to be sent, This includes the name and version of the library.
This PR also patches a number of situations that _could_ result in NaN values being sent to Raygun. The main areas changed are:
- Custom Timings and `AddMissingWRT` were accessing `offset` which is not always set. This now falls back to zero if no value exists
- Virtual Page Timings were accessing a browser API that is deprecated in some new browser updates, this now falls back to the new API

Addclient info to rum payload

---

CHANGELOG.md
package.json
src/raygun.breadcrumbs.js

This bug fixes a typo in the breadcrumbs code when it try's to fetch the URL for a failed request.
This bug was raised in https://github.com/MindscapeHQ/raygun4js/issues/508.
https://github.com/MindscapeHQ/raygun4js/blob/fe73f53dd0af9dd8002025eb6fdd13238eb01de9/src/raygun.breadcrumbs.js#L478
`error.requestUrl` should be `error.requestURL`

Fix typo in fetching XHR url for breadcrumbs 

---

.github/workflows/prerelease.yml
.github/workflows/tests.yml
CHANGELOG.md
package.json
src/raygun.tracekit.jquery.js
wdio.conf.js

[Issue raised by Mattybat on the Raygun forums.](https://raygun.com/forums/thread/143932)
See https://api.jquery.com/jQuery.isFunction/
> As of jQuery 3.3, `jQuery.isFunction()` has been deprecated. In most cases, its use can be replaced by `typeof x === "function"`.
---
This PR also
- allows Continuous Integration action to run without manually setting the chromedriver version in `package.json`,
- revives `prerelease.yml`.

Resolve jQuery isFunction warning

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.loader.js

This changes the way Ping happens by:
- Limiting ping to be once per session.
- Failure to ping will re-attempt at intervals of 10/20/40/80/120 seconds before stopping.
- Re-ping if `data` changes. This happens if the app sent `true` for rum and then changed to `false`, it would cause a re-ping to happens.

Limit Ping to be less frequent.

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum/index.js

This PR updates the details associated with RUM XHR events to include the original request details. These details are under a new `requestDetails` property and they include `url` (with query parameters), `method`, `body` and `responseBody`.  Request details are only present in the paylod until the `onBeforeSendRUM` handler has been called, after this they're stripped from the payload, so as to not be sent to Raygun's servers. The purpose of this change is to support hydrating certain request details into XHR events, should users wish to do this. As an example, we could now swap out the `url` of the xhr event , to be the one from `requestDetails`, so that it includes query parameters in Raygun.

RUM Before Send Handler Includes XHR Request Details
