MindscapeHQ/raygun4js

tracekit/README.md

Typo in title

---

README.md

Adding vuejs documentation

---

.gitattributes

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/279)

Mark dist as generated

---

tests/fixtures/v2/unhandledErrorWithUmdBuild.html
tests/specs/v2/payloadUnhandledErrorTests.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/321)

tests(umd): add test case to ensure umd build is functional

---

package.json
yarn.lock

Since this uses an environment variable, it fails on Windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/325)

chore(scripts): add cross-env to run test-local command

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec

Update version to 2.16.0

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.network-tracking.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4js/332)

fix(network-tracking): exception when calling text() on response stream

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.rum.js
src/raygun.utilities.js
tests/specs/v2/rumXhrStatusTracking.js
yarn.lock

Attaches the XHR asset type to missing WRT calls which are added when they are missing from performance API calls.

Bug Fix: Add XHR type to status codes

---

README.md

Temporarily removed the TravisCI build status pill until dependencies have been upgraded.

Tempoarily remove travisCI pill from readme.md

---

Gruntfile.js
src/helpers/window.js
src/raygun.rum/index.js
src/raygun.rum/rum.spec.js

Setups some unit testing in for RUM custom timing utility methods.

Custom timing utility tests

---

README.md

A quick documentation update to the disableErrorTracking feature to better describe the functionality it currently performs.

Readme update: disableErrorTracking option

---

package.json
yarn.lock

Upgrades the chromedriver dependancy to the latest version (85) to resolve the build failures.

Upgrade chrome driver to latest version

---

README.md

- Mention where in the head tag to include the snippet

Update to the installation instructions in the README.md

---

README.md

Update the readme with a description of the `trackViewportDimensions` option.

Update the readme with info about viewport tracking

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec
src/raygun.js
src/raygun.network-tracking.js
src/raygun.rum/core-web-vitals.js
src/raygun.rum/index.js

This PR adds a parent resource hash to assist with parenting resources worker-side.

Integrated a parent resource hash to assist with parenting

---

README.md

This PR updates the links in our readme to resolve this issue #431

Update script links in ReadMe

---

CHANGELOG.md
bower.json
package.json
raygun4js.nuspec

Bumped version number to create a release featuring this change: https://github.com/MindscapeHQ/raygun4js/pull/447

Bumped version to 2.25.2 for release

---

CHANGELOG.md
package.json

- Bumped version number and added change log to make a release featuring changes from: https://github.com/MindscapeHQ/raygun4js/pull/449

Bumped version to 2.25.3 for release

---

.github/workflows/tests.yml

* Specify Chrome version using their internal revision numbers
* Use older Node version for wdio compatibility
* Run grunt so that dist/raygun.js is available for the wdio suite

Fix issues with CI workflow

---

CHANGELOG.md
bower.json
package-lock.json
package.json
raygun4js.nuspec
src/raygun.loader.js
src/raygun.rum/index.js

Updated raygun4js to include High Entropy user agent data.
Due to changes made by the [chromium engine](https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-4) The UserAgent String no longer contains the correct OS version or the full browser version.
This PR uses the new `navigator.userAgentData` API to get this information.
Note: this API is not available in Firefox/gecko browsers. So FF will incorrectly report Win 11 as Win 10

Updated raygun4js to include High Entropy user agent data

---

.github/workflows/tests.yml
CHANGELOG.md
README.md
bower.json
package.json
raygun4js.nuspec

This PR is to clearly define the installation options available so that it's known that no installation of the NPM package is required via NPM.
**Screenshot** 📸 
Potentially how it could look -

[v2.25.7]: Clearly define options for installation and fix builds ✨🧹

---

README.md

This PR is to update the Vue section in the README to include appropriate instructions for Vue 2 and Vue 3

Update Vue.js documentation in README

---

CHANGELOG.md

[Ticket](https://raygun.atlassian.net/browse/WORM-248)
This needs to be done from the command line/online. 
This is a 'Line in the sand' commit to mark when we deprecated a number of versions in NPM and Nuget

Deprecate old packages on NPM and Nuget
